# Generated by Django 5.1.2 on 2024-11-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolioitem_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='images/defult.jpg', upload_to='images/'),
        ),
    ]
