# Generated by Django 5.1.2 on 2024-11-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
