# Generated by Django 5.1.2 on 2024-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('service', models.CharField(choices=[('web_development', 'Web Development'), ('seo_optimization', 'SEO Optimization'), ('web_maintenance', 'Web Maintenance'), ('ui_ux_design', 'UI/UX Design'), ('ci_cd', 'CI/CD'), ('responsive_design', 'Responsive Design'), ('inquiries', 'Inquiries')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
