# Generated by Django 5.1.2 on 2024-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('seo_optimization', 'SEO Optimization'), ('web_maintenance', 'Web Maintenance'), ('ui_ux_design', 'UI/UX Design'), ('ci_cd', 'CI/CD'), ('responsive_design', 'Responsive Design'), ('inquiries', 'Inquiries')], default='inquiries', max_length=50),
            preserve_default=False,
        ),
    ]
